version: "3"
services:
    worker:
        container_name: 'worker'
        depends_on:
            - db
            - redis
        build: ./worker/.
        networks:
            - front
            - back
    vote:
        container_name: 'voting-app'
        ports:
            - "80:80"
        build: ./vote/.
        depends_on:
            - redis
        networks:
            - front
    result:
        container_name: 'result-app'
        build: ./result/.
        ports:
            - "4000:4000"
        depends_on:
            - db
        networks:
            - back
    db:
        container_name: 'db'
        image: postgres:9.4
        environment: 
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
        networks:
            - back
    redis:
        container_name: 'redis'
        image: redis:5.0-alpine3.10
        networks:
            - front
networks:
    front:
    back: